# Schema for the configuration files of the Alps messages module.
alps_messages.settings:
  type: config_object
  label: 'Alps messages settings'
  mapping:
    message:
      type: string
      label: 'Message'
