#!/bin/bash

## Description: Run yarn commands
## Usage: theme [command]
## Example: "ddev theme build -- Read the HOW-TO.md for more commands"

yarn --cwd=web/themes/custom/alps_trips install
yarn --cwd=web/themes/custom/alps_trips $@
