version: '3.6'
services:
  next:
    command:
      - /bin/sh
      - -c
      - |
        yarn --cwd=app install
        yarn --cwd=app run dev
    container_name: "ddev-${DDEV_SITENAME}-next"
    expose:
      - "4000"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=4000:4000
      - HTTPS_EXPOSE=4001:4000
    image: node:18-buster-slim
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    volumes:
      - ".:/mnt/ddev_config"
      - "../next:/app"
